version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
  
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
