version: '3'

services:
  frontend:
    build:
      context: ./frontend2
      dockerfile: Dockerfile.frontend
    # command: tail -F anything
    ports: 
      - 3000:3000
    volumes:
      - ./frontend2/app:/src/frontend/app
      - /src/frontend/app/node_modules
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    command: tail -F anything
    volumes:
      - ./backend:/app/backend