version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: npm start
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
  
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: tail -F anything
    volumes:
      - ./backend:/app/backend