// On windows find at:
//    \\wsl$\Ubuntu\home\mkozi\git\udemy\udemy_CompleteGuideToBuildingAppWithNetReact


GET http://127.0.0.1:5000/api/Values

###

GET http://127.0.0.1:5000/api/Values/2